---
apiVersion: v1
kind: Secret
metadata:
  labels:
    provider: fabric8
    project: product-catalog-lab3
    version: 1.0.0
    group: com.redhat.coolstore
  name: my-database-secret
stringData:
  user: luke
  password: secret
